openapi: 3.0.0
info:
  title: week 11
  version: 1.0.0
servers:
  - url: http://localhost:8000
  - url: https://week10-reynaldofang.cyclic.cloud
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /register:
    post:
      tags:
        - default
      summary: register user deploy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: reynaldo
                password: reynaldo88
                role: maker
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: login user deploy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: jay
                password: reynaldo88
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /reset-password:
    post:
      tags:
        - default
      summary: login reset password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: reynaldo
                newPassword: rey123
                resetToken: >-
                  d97cef96e7b1bf23236fba320e2ab200eede07f1a1b381aeca35dd0341081527
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /reset-password-request:
    post:
      tags:
        - default
      summary: login reset request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: reynaldo
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /transfers/create:
    post:
      tags:
        - default
      summary: create transfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: jajan
                amount: 85000
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /transfers/transfer-list:
    get:
      tags:
        - default
      summary: get transfer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /transfers/change-status/64e903e90a2a7d63b6edc829:
    patch:
      tags:
        - default
      summary: update accept
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: accept
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
